// LOGIN
export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";


// SEND OTP
export const SEND_OTP_START = "SEND_OTP_START";
export const SEND_OTP_SUCCESS = "SEND_OTP_SUCCESS";
export const SEND_OTP_ERROR = "SEND_OTP_ERROR";


// VERIFY OTP
export const VERIFY_OTP_START = "VERIFY_OTP_START";
export const VERIFY_OTP_SUCCESS = "VERIFY_OTP_SUCCESS";
export const VERIFY_OTP_ERROR = "VERIFY_OTP_ERROR";


// CONTENT - CAROUSEL
export const FETCH_CAROUSEL_START = "FETCH_CAROUSEL_START";
export const FETCH_CAROUSEL_SUCCESS = "FETCH_CAROUSEL_SUCCESS";
export const FETCH_CAROUSEL_ERROR = "FETCH_CAROUSEL_ERROR";


// CONTENT - MOST LOVED
export const FETCH_MOST_LOVED_START = "FETCH_MOST_LOVED_START";
export const FETCH_MOST_LOVED_SUCCESS = "FETCH_MOST_LOVED_SUCCESS";
export const FETCH_MOST_LOVED_ERROR = "FETCH_MOST_LOVED_ERROR";

// CONTENT - OUR FACE BESTSELLERS
export const FETCH_OUR_FACE_START = "FETCH_OUR_FACE_START";
export const FETCH_OUR_FACE_SUCCESS = "FETCH_OUR_FACE_SUCCESS";
export const FETCH_OUR_FACE_ERROR = "FETCH_OUR_FACE_ERROR";

//CONTENT-OUR HAIR BESTSELLERS
export const FETCH_OUR_HAIR_START = "FETCH_OUR_HAIR_START";
export const FETCH_OUR_HAIR_SUCCESS = "FETCH_OUR_HAIR_SUCCESS";
export const FETCH_OUR_HAIR_ERROR = "FETCH_OUR_HAIR_ERROR";

// PRODUCT - CREATE

export const CREATE_PRODUCT_START =
  "CREATE_PRODUCT_START";

export const CREATE_PRODUCT_SUCCESS =
  "CREATE_PRODUCT_SUCCESS";

export const CREATE_PRODUCT_ERROR =
  "CREATE_PRODUCT_ERROR";


// PRODUCT - GET

export const FETCH_PRODUCTS_START =
  "FETCH_PRODUCTS_START";

export const FETCH_PRODUCTS_SUCCESS =
  "FETCH_PRODUCTS_SUCCESS";

export const FETCH_PRODUCTS_ERROR =
  "FETCH_PRODUCTS_ERROR";


// PRODUCT - CATEGORIES

export const FETCH_PRODUCT_CATEGORIES_START =
  "FETCH_PRODUCT_CATEGORIES_START";

export const FETCH_PRODUCT_CATEGORIES_SUCCESS =
  "FETCH_PRODUCT_CATEGORIES_SUCCESS";

export const FETCH_PRODUCT_CATEGORIES_ERROR =
  "FETCH_PRODUCT_CATEGORIES_ERROR";


export const FETCH_CATEGORIES_START =
  "FETCH_CATEGORIES_START";

export const FETCH_CATEGORIES_SUCCESS =
  "FETCH_CATEGORIES_SUCCESS";

export const FETCH_CATEGORIES_ERROR =
  "FETCH_CATEGORIES_ERROR";

  export const UPDATE_PRODUCT_START =
  "UPDATE_PRODUCT_START";

export const UPDATE_PRODUCT_SUCCESS =
  "UPDATE_PRODUCT_SUCCESS";

export const UPDATE_PRODUCT_ERROR =
  "UPDATE_PRODUCT_ERROR";


export const DELETE_PRODUCT_START =
  "DELETE_PRODUCT_START";

export const DELETE_PRODUCT_SUCCESS =
  "DELETE_PRODUCT_SUCCESS";

export const DELETE_PRODUCT_ERROR =
  "DELETE_PRODUCT_ERROR";

  // CONTENT - OUR BABY BESTSELLERS

export const FETCH_OUR_BABY_START =
  "FETCH_OUR_BABY_START";

export const FETCH_OUR_BABY_SUCCESS =
  "FETCH_OUR_BABY_SUCCESS";

export const FETCH_OUR_BABY_ERROR =
  "FETCH_OUR_BABY_ERROR";

  // CONTENT - SHOP BY INGREDIENTS

export const FETCH_SHOP_BY_INGREDIENTS_START =
  "FETCH_SHOP_BY_INGREDIENTS_START";

export const FETCH_SHOP_BY_INGREDIENTS_SUCCESS =
  "FETCH_SHOP_BY_INGREDIENTS_SUCCESS";

export const FETCH_SHOP_BY_INGREDIENTS_ERROR =
  "FETCH_SHOP_BY_INGREDIENTS_ERROR";

  // ========================================
// CONTENT - OUR MAKEUP BESTSELLERS
// ========================================

export const FETCH_OUR_MAKEUP_START =
  "FETCH_OUR_MAKEUP_START";

export const FETCH_OUR_MAKEUP_SUCCESS =
  "FETCH_OUR_MAKEUP_SUCCESS";

export const FETCH_OUR_MAKEUP_ERROR =
  "FETCH_OUR_MAKEUP_ERROR";